# Generated by Django 6.0.4 on 2026-05-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_pack_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fichier_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='courses.specialite'),
        ),
    ]
