# Generated by Django 6.0.4 on 2026-05-19 20:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_fichier_video_alter_pack_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cloudinary_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
