# Generated by Django 6.0.4 on 2026-05-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_cloudinary_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='fichier_video',
        ),
        migrations.AlterField(
            model_name='video',
            name='url_hebergement',
            field=models.URLField(blank=True, null=True),
        ),
    ]
